# 빌드 명령어
# docker-compose -f docker-compose-e2e-test.yaml build
# 시작 명령어
# docker-compose -f docker-compose-e2e-test.yaml up
# 종료 명령어
# docker-compose -f docker-compose-e2e-test.yaml down

version: '3.9'

services:
  mysql:
    image: mysql:8.0.31
    restart: always
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: kero
      MYSQL_USER: kero
      MYSQL_PASSWORD: kero
      MYSQL_DATABASE: kero

  app:
    build: .
    depends_on:
      - mysql
    command: sh -c "sleep 10s && npm run typeorm:migration:run && mv ./src/db-migrations ./ && npm run test:e2e"
